workflows:
  my-workflow:
    scripts:
      - name: Launch emulator
        script: |
          set -e # exit on first failed command

          cd $ANDROID_HOME/tools
          emulator -avd emulator &
          adb wait-for-device
